package tp_test1.junit.monprojet.test;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import junit.framework.Assert;
import tp_test1.junit.monprojet.SommeArgent;
import tp_test1.junit.monprojet.UniteDistincteException;

public class JUnit4 {
	private static int nbPassages = 0;
	
    private SommeArgent m12CHF;
    private SommeArgent m14CHF;
    private SommeArgent m14USD;

    @Before
    public void setUp() {
    	
    	
        m12CHF = new SommeArgent(12, "CHF");
        m14CHF = new SommeArgent(14, "CHF");
        m14USD = new SommeArgent(14, "USD");
        nbPassages++;
        System.out.println(nbPassages + "ème passage avant exécution d'une méthode de test");
    }
    
    @After
    public void tearDown() {
        System.out.println(nbPassages + "ème passage APRES exécution d'une méthode de test");
    }

    
	
	
	@Test(expected = UniteDistincteException.class)
	public void testAddUnitesDistinctes() throws UniteDistincteException {
	    SommeArgent m12CHF = new SommeArgent(12, "CHF");
	    SommeArgent m14USD = new SommeArgent(14, "USD");
	    SommeArgent m = m12CHF.add(m14USD);
	}
	
	@Test
	public void EqualsTest() {
		Assert.assertTrue(!m12CHF.equals(null));
		Assert.assertEquals(m12CHF, m12CHF);
		Assert.assertEquals(m12CHF, new SommeArgent(12, "CHF")); // (1)
		Assert.assertTrue(!m12CHF.equals(m14CHF));
		Assert.assertTrue(!m14USD.equals(m14CHF));
	}

}
